{{- range .Values.engines }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Values.engineServiceAccount }}
  namespace: benchmark-{{ . }}
  labels:
    {{- include "benchmark-tenancy.labels" $ | nindent 4 }}
    benchmark.datafusion.apache.org/engine: {{ . }}
---
{{- end }}
